name: morning

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16.x'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install Dependencies
        run: pip install -r ./requirements.txt

      - name: Send Morning Message
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          USER_ID: ${{ secrets.USER_ID }}
          START_DATE: ${{ secrets.START_DATE }}
          BIRTHDAY: ${{ secrets.BIRTHDAY }}
          CITY: ${{ secrets.CITY }}
        run: python ./main.py
