name: morning
on:
  schedule:
  - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
      - name: checkout
        uses: actions/checkout@v2.4.2

      - name: Setup Node.js
        uses: actions/setup-node@v2.6.4
        with:
          node-version: '16.x'

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies and run script
        run: |
          pip install -r ./requirements.txt
          python ./main.py

        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          USER_ID: ${{ secrets.USER_ID }}
          START_DATE: ${{ secrets.START_DATE }}
          BIRTHDAY: ${{ secrets.BIRTHDAY }}
          CITY: ${{ secrets.CITY }}

      - name: Save result to environment file
        run: |
          echo "RESULT=$(cat result.txt)" >> $GITHUB_ENV
          
      - name: Cleanup
        run: |
          rm result.txt
